/**
 * DRISHYAM visual reminder: The Evidence Archive — an editorial journey where one
 * physical evidence package travels along burgundy case threads into a legal report.
 */
import { useRef, useState } from "react";
import { AnimatePresence, motion, useMotionValueEvent, useScroll, useTransform } from "framer-motion";
import { AlertTriangle, Check, FileText, Fingerprint, Lock, Network, Search, Upload } from "lucide-react";

const stages = [
  { number: "01", title: "Upload", line: "Evidence received", detail: "A preserved file package enters the case with its original context intact.", icon: Upload, object: "folder" },
  { number: "02", title: "Validate", line: "Preserved + verified", detail: "Integrity checks seal the source and attach a traceable hash record.", icon: Lock, object: "lock" },
  { number: "03", title: "Extract", line: "Facts emerge", detail: "Text, timestamps, identifiers, and metadata leave the physical source as reviewable signals.", icon: Fingerprint, object: "extract" },
  { number: "04", title: "Normalize", line: "Structured events", detail: "Scattered facts align into common events the investigation can compare and trace.", icon: FileText, object: "normalize" },
  { number: "05", title: "Analyze", line: "Connections form", detail: "Entity nodes and evidence paths form an explainable relationship map.", icon: Network, object: "map" },
  { number: "06", title: "Alert", line: "Lead surfaced", detail: "A source-led anomaly is flagged for investigator review—not automated judgment.", icon: Search, object: "alert" },
  { number: "07", title: "Report", line: "Court ready", detail: "Reviewed evidence converges into one structured investigation report.", icon: Check, object: "report" },
];

function EvidenceScene({ stage }: { stage: number }) {
  const active = stages[stage];
  return <div className="journey-stage relative h-[330px] overflow-hidden rounded-[22px] border border-[#dfd4c5] bg-[#f4eee4] shadow-[0_24px_55px_rgba(84,60,32,.12)] lg:h-[380px]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_14%,rgba(180,119,96,.13),transparent_24%),radial-gradient(circle_at_84%_86%,rgba(182,151,103,.12),transparent_24%)]" />
    <div className="absolute left-6 top-6 z-10 max-w-[230px]"><p className="mono text-[9px] font-bold uppercase tracking-[.15em] text-[#7f1d1d]">Evidence journey / {active.number}</p><h3 className="display-serif mt-3 text-3xl tracking-[-.03em] text-[#29241f]">{active.line}</h3><p className="mt-3 text-[11px] leading-5 text-[#685f55]">{active.detail}</p></div>
    <div className="journey-dust absolute inset-0" aria-hidden="true"><i/><i/><i/><i/><i/></div>
    <AnimatePresence mode="wait"><motion.div key={stage} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -7 }} transition={{ duration: .34, ease: [0.23, 1, 0.32, 1] }} className="absolute inset-0">
    {stage === 0 && <div className="absolute bottom-7 right-7 h-[210px] w-[39%] min-w-[190px] sm:right-12 sm:w-[41%]"><motion.div animate={{ rotate: [0, 4, 0], y: [0, -5, 0] }} transition={{ duration: 3.6, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-4 right-2 grid h-28 w-32 place-items-center rounded-2xl border border-[#ceb69d] bg-[#fff9ef] shadow-[0_18px_30px_rgba(90,57,30,.13)]"><Upload size={30} className="text-[#7f1d1d]"/><span className="mono text-[8px] font-bold tracking-[.15em] text-[#7f1d1d]">SOURCE</span></motion.div></div>}
    {stage === 1 && <div className="absolute bottom-7 right-7 h-[210px] w-[39%] min-w-[190px] sm:right-12 sm:w-[41%]"><motion.div animate={{ rotate: 360 }} transition={{ duration: 9, repeat: Infinity, ease: "linear" }} className="absolute bottom-[48px] left-3 h-32 w-32 rounded-full border border-dashed border-[#aa6a62]"/><motion.div animate={{ scale: [.92, 1.06, .92], opacity: [.35, .88, .35] }} transition={{ duration: 2.2, repeat: Infinity }} className="absolute bottom-[52px] left-7 h-24 w-24 rounded-full border-2 border-[#7f1d1d]/50"/><div className="absolute bottom-[68px] left-[44px] grid h-20 w-20 place-items-center rounded-full border border-[#d2b9a2] bg-[#fffaf2] shadow-[0_14px_26px_rgba(90,57,30,.13)]"><Lock size={28} className="text-[#7f1d1d]"/><span className="mono text-[7px] font-bold tracking-[.12em] text-[#7f1d1d]">VERIFIED</span></div><motion.div animate={{ x: [0, 9, 0], opacity: [.5, 1, .5] }} transition={{ duration: 2.1, repeat: Infinity }} className="absolute bottom-2 right-0 rounded-full border border-[#dcc8b4] bg-[#f8ecdf] px-3 py-2 mono text-[8px] font-bold text-[#7f1d1d]">HASH / 67E1B803</motion.div></div>}
    {stage === 2 && <div className="absolute bottom-7 right-7 h-[210px] w-[39%] min-w-[190px] sm:right-12 sm:w-[41%]"><div className="absolute bottom-4 right-3 grid h-28 w-24 place-items-center rounded-xl border border-[#d5c1ab] bg-[#fffaf2] shadow-[0_12px_24px_rgba(84,60,32,.12)]"><Fingerprint size={27} className="text-[#7f1d1d]"/><span className="mono text-[7px] font-bold text-[#7f1d1d]">RAW FILE</span></div>{["10:42", "UPI ID", "PHONE", "URL"].map((chip, index) => <motion.span key={chip} initial={{ opacity: 0, x: 10, y: 8 }} animate={{ opacity: [0, 1, 1, 0], x: [10, -20 - index * 7, -46 - index * 7, -62 - index * 7], y: [8, -3 - index * 18, -18 - index * 20, -30 - index * 20] }} transition={{ duration: 3.3, delay: index * .42, repeat: Infinity, repeatDelay: .7 }} className="absolute bottom-[72px] right-[24px] rounded-md border border-[#dfcbb8] bg-[#f9efe3] px-2 py-1 mono text-[8px] font-bold text-[#7f1d1d]">{chip}</motion.span>)}</div>}
    {stage === 3 && <><div className="journey-normalize absolute bottom-10 right-7 grid w-[62%] grid-cols-2 gap-2 sm:right-14 sm:w-[48%]"><motion.div animate={{ x: [-20, 0], y: [16, 0], rotate: [-8, 0] }} transition={{ duration: .75 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:11</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Message received</p></motion.div><motion.div animate={{ x: [18, 0], y: [-14, 0], rotate: [7, 0] }} transition={{ duration: .75 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:42</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Payment initiated</p></motion.div><motion.div animate={{ x: [-16, 0], y: [-8, 0], rotate: [-6, 0] }} transition={{ duration: .75, delay: .08 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:48</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Bank debit confirmed</p></motion.div><motion.div animate={{ x: [22, 0], y: [12, 0], rotate: [8, 0] }} transition={{ duration: .75, delay: .08 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">11:04</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Review gap found</p></motion.div></div></>}
    {stage === 4 && <div className="absolute bottom-7 right-7 h-[210px] w-[42%] min-w-[205px] sm:right-12 sm:w-[43%]"><svg viewBox="0 0 310 190" className="absolute inset-0 h-full w-full" aria-hidden="true"><motion.path d="M38 138 C78 85 121 103 162 114 S221 58 264 70 M162 114 C198 163 242 164 278 142" fill="none" stroke="#8a2722" strokeWidth="2" strokeDasharray="4 7" animate={{ strokeDashoffset: [0, -42] }} transition={{ duration: 2.8, repeat: Infinity, ease: "linear" }}/></svg><motion.span animate={{ scale: [1, 1.12, 1] }} transition={{ duration: 1.8, repeat: Infinity }} style={{ left: "12.3%", top: "72.5%" }} className="absolute grid h-10 w-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#fff9f0] text-[9px] font-extrabold text-[#7f1d1d] shadow-[0_8px_16px_rgba(127,29,29,.14)]">•</motion.span><motion.span animate={{ scale: [1, 1.12, 1] }} transition={{ duration: 2, delay: .15, repeat: Infinity }} style={{ left: "30.3%", top: "47%" }} className="absolute grid h-10 w-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#fff9f0] text-[9px] font-extrabold text-[#7f1d1d] shadow-[0_8px_16px_rgba(127,29,29,.14)]">•</motion.span><motion.span animate={{ scale: [1, 1.25, 1] }} transition={{ duration: 1.8, delay: .3, repeat: Infinity }} style={{ left: "52.3%", top: "60%" }} className="absolute grid h-12 w-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#7f1d1d] text-[9px] font-extrabold text-white shadow-[0_8px_16px_rgba(127,29,29,.2)]">01</motion.span><motion.span animate={{ scale: [1, 1.12, 1] }} transition={{ duration: 2.15, delay: .45, repeat: Infinity }} style={{ left: "72.2%", top: "37%" }} className="absolute grid h-10 w-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#fff9f0] text-[9px] font-extrabold text-[#7f1d1d] shadow-[0_8px_16px_rgba(127,29,29,.14)]">•</motion.span><motion.span animate={{ scale: [1, 1.12, 1] }} transition={{ duration: 1.9, delay: .6, repeat: Infinity }} style={{ left: "89.7%", top: "74.5%" }} className="absolute grid h-10 w-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#fff9f0] text-[9px] font-extrabold text-[#7f1d1d] shadow-[0_8px_16px_rgba(127,29,29,.14)]">•</motion.span></div>}
    {stage === 5 && <div className="absolute bottom-7 right-7 h-[210px] w-[39%] min-w-[190px] sm:right-12 sm:w-[41%]"><motion.div animate={{ scale: [.8, 1.18, .8], opacity: [.12, .45, .12] }} transition={{ duration: 2.4, repeat: Infinity }} className="absolute bottom-[47px] left-4 h-32 w-32 rounded-full border-2 border-[#9d312b]"/><motion.div animate={{ scale: [.76, 1.1, .76], opacity: [.18, .55, .18] }} transition={{ duration: 2.4, delay: .35, repeat: Infinity }} className="absolute bottom-[59px] left-10 h-24 w-24 rounded-full border border-[#c26b61]"/><motion.div animate={{ rotate: [-3, 3, -3], y: [0, -5, 0] }} transition={{ duration: 2.6, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-[79px] left-[52px] grid h-16 w-16 place-items-center rounded-xl bg-[#8a2722] text-white shadow-[0_14px_25px_rgba(127,29,29,.26)]"><AlertTriangle size={27}/></motion.div><motion.span animate={{ x: [0, 8, 0], opacity: [.55, 1, .55] }} transition={{ duration: 1.7, repeat: Infinity }} className="absolute bottom-3 right-0 rounded-md border border-[#d3a9a1] bg-[#fff5ee] px-3 py-2 mono text-[8px] font-bold tracking-[.1em] text-[#8a2722]">LEAD FLAGGED</motion.span></div>}
    {stage === 6 && <div className="absolute bottom-7 right-7 h-[210px] w-[39%] min-w-[190px] sm:right-12 sm:w-[41%]"><motion.div animate={{ y: [9, 0, 9], rotate: [-3, -1, -3] }} transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-3 right-3 h-36 w-28 rounded-xl border border-[#cdb69e] bg-[#f6eadb] shadow-[0_14px_28px_rgba(82,55,28,.12)]"/><motion.div animate={{ y: [5, -4, 5], rotate: [3, 0, 3] }} transition={{ duration: 3.4, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-10 right-16 h-36 w-28 rounded-xl border border-[#d8c4ad] bg-[#fff9f0] shadow-[0_16px_30px_rgba(82,55,28,.14)]"><span className="absolute left-5 right-5 top-8 h-px bg-[#c7ab91]"/><span className="absolute left-5 right-9 top-14 h-px bg-[#c7ab91]"/><span className="absolute left-5 right-7 top-20 h-px bg-[#c7ab91]"/><motion.span animate={{ scale: [.92, 1.08, .92] }} transition={{ duration: 1.9, repeat: Infinity }} className="absolute bottom-6 left-6 grid h-11 w-20 place-items-center rounded border-2 border-[#9d312b] text-[8px] font-extrabold tracking-[.12em] text-[#9d312b]">REVIEWED</motion.span></motion.div><motion.div animate={{ rotate: [0, 8, 0] }} transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-2 right-0 grid h-12 w-12 place-items-center rounded-full border border-[#d2b395] bg-[#7f1d1d] text-white"><Check size={22}/></motion.div></div>}
    </motion.div></AnimatePresence>
  </div>;
}

export default function InvestigationJourney() {
  const container = useRef<HTMLElement>(null);
  const [active, setActive] = useState(0);
  const [hovered, setHovered] = useState<number | null>(null);
  const { scrollYProgress } = useScroll({ target: container, offset: ["start start", "end end"] });
  const stageThresholds = [0, .16, .32, .48, .64, .8, .96];
  const stagePositions = [
    "calc(1.25rem + (100% - 2.5rem) * .0714286)",
    "calc(1.25rem + (100% - 2.5rem) * .2142857)",
    "calc(1.25rem + (100% - 2.5rem) * .3571429)",
    "calc(1.25rem + (100% - 2.5rem) * .5)",
    "calc(1.25rem + (100% - 2.5rem) * .6428571)",
    "calc(1.25rem + (100% - 2.5rem) * .7857143)",
    "calc(1.25rem + (100% - 2.5rem) * .9285714)",
  ];
  const progressWidth = useTransform(scrollYProgress, [0, 1], ["0%", "85%"]);
  const capsulePosition = useTransform(scrollYProgress, stageThresholds, stagePositions);
  useMotionValueEvent(scrollYProgress, "change", (value) => { const next = stageThresholds.reduce((stage, threshold, index) => value >= threshold ? index : stage, 0); setActive((current) => current === next ? current : next); });
  const jumpToStage = (index: number) => {
    const section = container.current;
    if (!section) return;
    const sectionTop = window.scrollY + section.getBoundingClientRect().top;
    const travel = Math.max(1, section.offsetHeight - window.innerHeight);
    const target = sectionTop + travel * Math.min(.995, stageThresholds[index]);
    setHovered(null);
    setActive(index);
    window.scrollTo({ top: target, behavior: "smooth" });
  };
  const preview = hovered ?? active;
  return <section ref={container} id="workflow" className="journey-shell relative mx-auto max-w-[1380px] px-6 py-24 lg:px-10 lg:py-32">
    <div className="journey-sticky relative">
      <div className="text-center"><div className="inline-flex items-center gap-3 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#7f1d1d]"><span className="h-px w-9 bg-[#7f1d1d]"/>How it works<span className="h-px w-9 bg-[#7f1d1d]"/></div><h2 className="display-serif mt-6 text-5xl tracking-[-.035em]">Watch a file become a finding.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-[#686056]">One preserved evidence package travels through validation, extraction, analysis, and review before becoming a court-ready investigation record.</p></div>
      <div className="journey-content-grid mt-12 grid gap-8 xl:grid-cols-[1.08fr_.92fr]"><EvidenceScene stage={preview}/><div className="journey-state-card flex h-[330px] flex-col rounded-[20px] border border-[#e1d6c6] bg-[#fffaf2]/75 p-5 shadow-[0_18px_38px_rgba(87,61,32,.08)] sm:p-7 lg:h-[380px]"><div className="flex items-center justify-between"><div><p className="mono text-[9px] font-bold uppercase tracking-[.15em] text-[#7f1d1d]">Live evidence state</p><motion.p key={preview} initial={{ opacity: 0, y: 7 }} animate={{ opacity: 1, y: 0 }} className="mt-2 text-lg font-extrabold text-[#312923]">{stages[preview].title}</motion.p></div><motion.div animate={{ scale: [1, 1.06, 1] }} transition={{ duration: 1.8, repeat: Infinity }} className="grid h-10 w-10 place-items-center rounded-full border border-[#d8c8b6] bg-[#f7efe4] text-[#7f1d1d]">{(() => { const Icon = stages[preview].icon; return <Icon size={18}/>; })()}</motion.div></div><motion.div key={`detail-${preview}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3 }} className="mt-7 rounded-xl border border-[#e3d7c8] bg-[#f8f2e9] p-4"><p className="text-[10px] leading-5 text-[#6b6258]">{stages[preview].detail}</p><div className="mt-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#7f1d1d]"/><span className="mono text-[9px] font-bold text-[#7f1d1d]">CASE PATH / {String(preview + 1).padStart(2, "0")} OF 07</span></div></motion.div><p className="mt-auto text-[10px] leading-5 text-[#7b7268]">Scroll is the journey controller. Hover a node only previews its evidence state.</p></div></div>
      <div className="journey-rail relative mt-14 overflow-x-auto pb-3"><div className="relative min-w-[920px] px-5 md:min-w-0"><div className="journey-track absolute left-[7.5%] right-[7.5%] top-10 h-[2px] bg-[#d4c5b3]"/><motion.div style={{ width: progressWidth }} className="journey-progress absolute left-[7.5%] top-10 h-[2px] bg-[#7f1d1d]"/><motion.div style={{ left: capsulePosition }} className="journey-capsule absolute top-[26px] z-10 h-7 w-7 -translate-x-1/2 rounded-full border-2 border-[#7f1d1d] bg-[#fffaf1] shadow-[0_4px_12px_rgba(127,29,29,.18)]"><span className="absolute inset-[5px] rounded-full bg-[#7f1d1d]"/></motion.div><div className="journey-steps relative grid grid-cols-7 gap-3">{stages.map((stage, index) => { const Icon = stage.icon; const state = index < active ? "complete" : index === active ? "active" : "future"; return <button key={stage.number} onClick={() => jumpToStage(index)} onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)} onFocus={() => setHovered(index)} onBlur={() => setHovered(null)} className={`journey-step journey-${state} group relative pt-[77px] text-center`}><motion.span whileHover={{ y: -5, scale: 1.04 }} className="journey-step-node absolute left-1/2 top-0 grid h-20 w-20 -translate-x-1/2 place-items-center rounded-full border-2 bg-[#f8f4ec] text-[#665d54] shadow-[0_6px_14px_rgba(79,57,33,.07)]"><span className="mono text-sm">{stage.number}</span><Icon className="absolute bottom-2.5 opacity-0 transition-opacity group-hover:opacity-100" size={13}/></motion.span><motion.p animate={{ y: state === "active" ? -2 : 0, opacity: state === "future" ? .62 : 1 }} className="text-sm font-extrabold text-[#2f2b26]">{stage.title}</motion.p><motion.p animate={{ opacity: state === "active" ? 1 : .62 }} className="mx-auto mt-2 max-w-[125px] text-[10px] leading-5 text-[#776e64]">{stage.line}</motion.p></button>})}</div></div></div>
    </div>
  </section>;
}
