/**
 * DRISHYAM visual reminder: The Evidence Archive — an editorial journey where one
 * physical evidence package travels along burgundy case threads into a legal report.
 */
import { useRef, useState } from "react";
import { AnimatePresence, motion, useMotionValueEvent, useScroll, useTransform } from "framer-motion";
import { AlertTriangle, Check, FileText, Fingerprint, Lock, Network, Search, Upload } from "lucide-react";

const ASSETS = {
  folder: "/manus-storage/workspace-evidence-folder_3446f4da.png",
  lock: "/manus-storage/reference-lock_76ff28d8.png",
  usb: "/manus-storage/reference-usb_ac806955.png",
  map: "/manus-storage/workspace-map-board_c063d31f.png",
  magnifier: "/manus-storage/workspace-magnifier_e87df5c6.png",
  report: "/manus-storage/workspace-report_b3c8d11a.png",
  fingerprint: "/manus-storage/reference-fingerprint_4cf2ff3f.png",
};

const stages = [
  { number: "01", title: "Upload", line: "Evidence received", detail: "A preserved file package enters the case with its original context intact.", icon: Upload, object: "folder" },
  { number: "02", title: "Validate", line: "Preserved + verified", detail: "Integrity checks seal the source and attach a traceable hash record.", icon: Lock, object: "lock" },
  { number: "03", title: "Extract", line: "Facts emerge", detail: "Text, timestamps, identifiers, and metadata leave the physical source as reviewable signals.", icon: Fingerprint, object: "extract" },
  { number: "04", title: "Normalize", line: "Structured events", detail: "Scattered facts align into common events the investigation can compare and trace.", icon: FileText, object: "normalize" },
  { number: "05", title: "Analyze", line: "Connections form", detail: "Entity nodes and evidence paths form an explainable relationship map.", icon: Network, object: "map" },
  { number: "06", title: "Alert", line: "Lead surfaced", detail: "A source-led anomaly is flagged for investigator review—not automated judgment.", icon: Search, object: "alert" },
  { number: "07", title: "Report", line: "Court ready", detail: "Reviewed evidence converges into one structured investigation report.", icon: Check, object: "report" },
];

function EvidenceScene({ stage }: { stage: number }) {
  const active = stages[stage];
  return <div className="journey-stage relative h-[330px] overflow-hidden rounded-[22px] border border-[#dfd4c5] bg-[#f4eee4] shadow-[0_24px_55px_rgba(84,60,32,.12)] lg:h-[380px]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_14%,rgba(180,119,96,.13),transparent_24%),radial-gradient(circle_at_84%_86%,rgba(182,151,103,.12),transparent_24%)]" />
    <div className="absolute left-6 top-6 z-10 max-w-[230px]"><p className="mono text-[9px] font-bold uppercase tracking-[.15em] text-[#7f1d1d]">Evidence journey / {active.number}</p><h3 className="display-serif mt-3 text-3xl tracking-[-.03em] text-[#29241f]">{active.line}</h3><p className="mt-3 text-[11px] leading-5 text-[#685f55]">{active.detail}</p></div>
    <div className="journey-dust absolute inset-0" aria-hidden="true"><i/><i/><i/><i/><i/></div>
    <AnimatePresence mode="wait"><motion.div key={stage} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -7 }} transition={{ duration: .34, ease: [0.23, 1, 0.32, 1] }} className="absolute inset-0">
    {stage === 0 && <><motion.img initial={{ x: -40, opacity: 0, rotate: -4 }} animate={{ x: 0, opacity: 1, rotate: 0 }} transition={{ type: "spring", stiffness: 105, damping: 18 }} src={ASSETS.folder} alt="Evidence folder arrives" className="absolute bottom-[-19%] right-[8%] w-[290px] sm:bottom-[-28%] sm:w-[375px]"/><motion.img animate={{ y: [0, -8, 0], rotate: [-5, 0, -5] }} transition={{ duration: 3.4, repeat: Infinity, ease: "easeInOut" }} src={ASSETS.usb} alt="USB evidence" className="absolute bottom-7 right-[31%] w-16 rotate-[-5deg] sm:w-20"/><span className="journey-particle bottom-24 right-[20%]"/><span className="journey-particle bottom-32 right-[28%]"/><span className="journey-particle bottom-16 right-[35%]"/></>}
    {stage === 1 && <><motion.img animate={{ scale: [1, 1.035, 1], rotate: [0, -1, 0] }} transition={{ duration: 2.5, repeat: Infinity, ease: "easeInOut" }} src={ASSETS.folder} alt="Sealed evidence folder" className="absolute bottom-[-21%] right-[13%] w-[305px] sm:bottom-[-25%] sm:w-[380px]"/><motion.div animate={{ scale: [0.92, 1.06, 0.92], opacity: [.45, .9, .45] }} transition={{ duration: 2.3, repeat: Infinity }} className="absolute bottom-[23%] right-[27%] grid h-24 w-24 place-items-center rounded-full border-2 border-[#7f1d1d] bg-[#fffaf0]/60 shadow-[0_0_0_11px_rgba(127,29,29,.07)]"><Lock size={28} className="text-[#7f1d1d]"/></motion.div><span className="journey-hash bottom-[19%] right-[8%]">SHA-256 / 67E1B803 / VERIFIED</span></>}
    {stage === 2 && <><img src={ASSETS.folder} alt="Opened evidence file" className="absolute bottom-[-25%] right-[9%] w-[330px] rotate-[-3deg] sm:w-[410px]"/><div className="journey-extract absolute bottom-[18%] right-[10%]"><motion.span animate={{ y: [0, -42], opacity: [0, 1, 0] }} transition={{ duration: 2.6, repeat: Infinity, delay: .1 }}>+91 98765 43210</motion.span><motion.span animate={{ y: [0, -66], opacity: [0, 1, 0] }} transition={{ duration: 2.6, repeat: Infinity, delay: .6 }}>10:42 IST</motion.span><motion.span animate={{ y: [0, -37], opacity: [0, 1, 0] }} transition={{ duration: 2.6, repeat: Infinity, delay: 1.1 }}>job-offer[.]in</motion.span><motion.span animate={{ y: [0, -77], opacity: [0, 1, 0] }} transition={{ duration: 2.6, repeat: Infinity, delay: 1.5 }}>₹30,000</motion.span></div><img src={ASSETS.fingerprint} alt="Fingerprint evidence" className="absolute bottom-[-7%] right-[35%] w-24 rotate-[7deg] opacity-75"/></>}
    {stage === 3 && <><div className="journey-normalize absolute bottom-10 right-7 grid w-[62%] grid-cols-2 gap-2 sm:right-14 sm:w-[48%]"><motion.div animate={{ x: [-20, 0], y: [16, 0], rotate: [-8, 0] }} transition={{ duration: .75 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:11</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Message received</p></motion.div><motion.div animate={{ x: [18, 0], y: [-14, 0], rotate: [7, 0] }} transition={{ duration: .75 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:42</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Payment initiated</p></motion.div><motion.div animate={{ x: [-16, 0], y: [-8, 0], rotate: [-6, 0] }} transition={{ duration: .75, delay: .08 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">10:48</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Bank debit confirmed</p></motion.div><motion.div animate={{ x: [22, 0], y: [12, 0], rotate: [8, 0] }} transition={{ duration: .75, delay: .08 }} className="rounded-lg border border-[#ddcfbd] bg-[#fffaf2] p-3 shadow-sm"><p className="mono text-[8px] text-[#7f1d1d]">11:04</p><p className="mt-1 text-[9px] font-bold text-[#3c332b]">Review gap found</p></motion.div></div><img src={ASSETS.usb} alt="Evidence package" className="absolute bottom-8 right-[68%] w-16 -rotate-[18deg] opacity-75"/></>}
    {stage === 4 && <><img src={ASSETS.map} alt="Connected evidence map" className="absolute bottom-[-25%] right-[-1%] w-[76%] opacity-90 sm:bottom-[-32%] sm:w-[68%]"/><svg viewBox="0 0 480 250" className="journey-graph absolute bottom-5 right-4 h-[64%] w-[68%]" aria-hidden="true"><path d="M78 148 C143 86 198 103 250 133 S337 95 408 74"/><path d="M250 133 C289 181 339 191 404 184"/><circle cx="78" cy="148" r="8"/><circle cx="176" cy="102" r="8"/><circle cx="250" cy="133" r="10"/><circle cx="408" cy="74" r="8"/><circle cx="404" cy="184" r="8"/></svg><div className="absolute bottom-[20%] right-[15%] grid grid-cols-3 gap-2 text-center"><span className="journey-node-label">PHONE</span><span className="journey-node-label">UPI</span><span className="journey-node-label">URL</span></div></>}
    {stage === 5 && <><img src={ASSETS.map} alt="Evidence map under review" className="absolute bottom-[-28%] right-[-3%] w-[72%] opacity-60"/><motion.img animate={{ rotate: [-8, 2, -8], x: [0, 5, 0] }} transition={{ duration: 3.2, repeat: Infinity, ease: "easeInOut" }} src={ASSETS.magnifier} alt="Magnifying glass reviews link" className="absolute bottom-[-8%] right-[14%] w-[210px] sm:w-[250px]"/><motion.div animate={{ scale: [1, 1.04, 1], boxShadow: ["0 12px 30px rgba(127,29,29,.12)", "0 16px 38px rgba(127,29,29,.25)", "0 12px 30px rgba(127,29,29,.12)"] }} transition={{ duration: 2.2, repeat: Infinity }} className="absolute bottom-7 right-5 max-w-[176px] rounded-lg border border-[#c98e84] bg-[#fff7ef] p-3"><div className="flex items-center gap-2 text-[#8a2722]"><AlertTriangle size={14}/><p className="text-[9px] font-extrabold uppercase tracking-[.1em]">Investigation alert</p></div><p className="mt-2 text-[10px] font-bold text-[#44342e]">Suspicious link detected</p></motion.div></>}
    {stage === 6 && <><motion.img initial={{ y: 36, opacity: 0, rotate: -4 }} animate={{ y: [0, -8, 0], opacity: 1, rotate: [0, .8, 0] }} transition={{ duration: 3.3, repeat: Infinity, ease: "easeInOut" }} src={ASSETS.report} alt="Court ready investigation report" className="absolute bottom-[-20%] right-[7%] w-[330px] sm:bottom-[-27%] sm:w-[430px]"/><motion.div initial={{ scale: .86, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ delay: .25, duration: .55 }} className="absolute bottom-[22%] right-[13%] rotate-[-8deg] border-2 border-[#9d312b] px-3 py-1 text-[11px] font-extrabold tracking-[.12em] text-[#9d312b]">COURT READY</motion.div><div className="absolute bottom-[17%] right-[58%] flex gap-1"><span className="journey-page"/><span className="journey-page journey-page-delay"/><span className="journey-page journey-page-delay-2"/></div></>}
    </motion.div></AnimatePresence>
  </div>;
}

export default function InvestigationJourney() {
  const container = useRef<HTMLElement>(null);
  const [active, setActive] = useState(0);
  const [hovered, setHovered] = useState<number | null>(null);
  const { scrollYProgress } = useScroll({ target: container, offset: ["start start", "end end"] });
  const progressWidth = useTransform(scrollYProgress, [0, 1], ["0%", "85%"]);
  const capsulePosition = useTransform(scrollYProgress, [0, 1], ["7.5%", "92.5%"]);
  const stageThresholds = [0, .16, .32, .48, .64, .8, .96];
  useMotionValueEvent(scrollYProgress, "change", (value) => { const next = stageThresholds.reduce((stage, threshold, index) => value >= threshold ? index : stage, 0); setActive((current) => current === next ? current : next); });
  const jumpToStage = (index: number) => {
    const section = container.current;
    if (!section) return;
    const sectionTop = window.scrollY + section.getBoundingClientRect().top;
    const travel = Math.max(1, section.offsetHeight - window.innerHeight);
    const target = sectionTop + travel * Math.min(.995, stageThresholds[index]);
    setHovered(null);
    setActive(index);
    window.scrollTo({ top: target, behavior: "smooth" });
  };
  const preview = hovered ?? active;
  return <section ref={container} id="workflow" className="journey-shell relative mx-auto max-w-[1380px] px-6 py-24 lg:px-10 lg:py-32">
    <img src={ASSETS.fingerprint} alt="Fingerprint source evidence" className="journey-decor-left evidence-object evidence-float pointer-events-none absolute -left-24 hidden w-44 rotate-[-10deg] opacity-55 xl:block" />
    <img src={ASSETS.folder} alt="Evidence package" className="journey-decor-right evidence-object evidence-drift pointer-events-none absolute -right-28 hidden w-56 rotate-[9deg] opacity-40 xl:block" />
    <div className="journey-sticky relative">
      <div className="text-center"><div className="inline-flex items-center gap-3 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#7f1d1d]"><span className="h-px w-9 bg-[#7f1d1d]"/>How it works<span className="h-px w-9 bg-[#7f1d1d]"/></div><h2 className="display-serif mt-6 text-5xl tracking-[-.035em]">Watch a file become a finding.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-[#686056]">One preserved evidence package travels through validation, extraction, analysis, and review before becoming a court-ready investigation record.</p></div>
      <div className="journey-content-grid mt-12 grid gap-8 xl:grid-cols-[1.08fr_.92fr]"><EvidenceScene stage={preview}/><div className="journey-state-card flex h-[330px] flex-col rounded-[20px] border border-[#e1d6c6] bg-[#fffaf2]/75 p-5 shadow-[0_18px_38px_rgba(87,61,32,.08)] sm:p-7 lg:h-[380px]"><div className="flex items-center justify-between"><div><p className="mono text-[9px] font-bold uppercase tracking-[.15em] text-[#7f1d1d]">Live evidence state</p><motion.p key={preview} initial={{ opacity: 0, y: 7 }} animate={{ opacity: 1, y: 0 }} className="mt-2 text-lg font-extrabold text-[#312923]">{stages[preview].title}</motion.p></div><motion.div animate={{ scale: [1, 1.06, 1] }} transition={{ duration: 1.8, repeat: Infinity }} className="grid h-10 w-10 place-items-center rounded-full border border-[#d8c8b6] bg-[#f7efe4] text-[#7f1d1d]">{(() => { const Icon = stages[preview].icon; return <Icon size={18}/>; })()}</motion.div></div><motion.div key={`detail-${preview}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3 }} className="mt-7 rounded-xl border border-[#e3d7c8] bg-[#f8f2e9] p-4"><p className="text-[10px] leading-5 text-[#6b6258]">{stages[preview].detail}</p><div className="mt-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#7f1d1d]"/><span className="mono text-[9px] font-bold text-[#7f1d1d]">CASE PATH / {String(preview + 1).padStart(2, "0")} OF 07</span></div></motion.div><p className="mt-auto text-[10px] leading-5 text-[#7b7268]">Scroll is the journey controller. Hover a node only previews its evidence state.</p></div></div>
      <div className="journey-rail relative mt-14 overflow-x-auto pb-3"><div className="relative min-w-[920px] px-5 md:min-w-0"><div className="journey-track absolute left-[7.5%] right-[7.5%] top-10 h-[2px] bg-[#d4c5b3]"/><motion.div style={{ width: progressWidth }} className="journey-progress absolute left-[7.5%] top-10 h-[2px] bg-[#7f1d1d]"/><motion.div style={{ left: capsulePosition }} className="journey-capsule absolute top-[27px] z-10 h-7 w-7 -translate-x-1/2 rounded-full border-2 border-[#7f1d1d] bg-[#fffaf1] shadow-[0_4px_12px_rgba(127,29,29,.18)]"><span className="absolute inset-[5px] rounded-full bg-[#7f1d1d]"/></motion.div><div className="journey-steps relative grid grid-cols-7 gap-3">{stages.map((stage, index) => { const Icon = stage.icon; const state = index < active ? "complete" : index === active ? "active" : "future"; return <button key={stage.number} onClick={() => jumpToStage(index)} onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)} onFocus={() => setHovered(index)} onBlur={() => setHovered(null)} className={`journey-step journey-${state} group relative pt-[77px] text-center`}><motion.span whileHover={{ y: -5, scale: 1.04 }} className="journey-step-node absolute left-1/2 top-0 grid h-20 w-20 -translate-x-1/2 place-items-center rounded-full border-2 bg-[#f8f4ec] text-[#665d54] shadow-[0_6px_14px_rgba(79,57,33,.07)]"><span className="mono text-sm">{stage.number}</span><Icon className="absolute bottom-2.5 opacity-0 transition-opacity group-hover:opacity-100" size={13}/></motion.span><motion.p animate={{ y: state === "active" ? -2 : 0, opacity: state === "future" ? .62 : 1 }} className="text-sm font-extrabold text-[#2f2b26]">{stage.title}</motion.p><motion.p animate={{ opacity: state === "active" ? 1 : .62 }} className="mx-auto mt-2 max-w-[125px] text-[10px] leading-5 text-[#776e64]">{stage.line}</motion.p></button>})}</div></div></div>
    </div>
  </section>;
}
