/**
 * DRISHYAM visual reminder: Public-only fictional case preview — ivory evidence sheets,
 * burgundy source trails, and restrained interaction. This component never calls the API.
 */
import { useMemo, useState } from "react";
import { Activity, AlertTriangle, CircleDollarSign, Clock, Database, Eye, FileText, Files, Globe, Landmark, Link2, Network, Search, ShieldCheck, Sparkles } from "lucide-react";

type Pane = "Overview" | "Timeline" | "Entity graph" | "Transaction trail" | "Alerts" | "Evidence vault" | "Report builder";

const panes: Pane[] = ["Overview", "Timeline", "Entity graph", "Transaction trail", "Alerts", "Evidence vault", "Report builder"];
const timeline = [
  ["10:11", "WhatsApp message received", "New job offer linked to +91 98765 43210", "chat_export.txt", "94%"],
  ["10:16", "Phishing link shared", "Domain job-offer[.]in added to source entity", "chat_export.txt", "88%"],
  ["10:42", "UPI payment initiated", "₹30,000 paid to r***l@okaxis · UTR 89122A", "upi_receipt.png", "97%"],
  ["10:48", "Bank debit confirmed", "Transaction reference linked to bank statement", "bank_may.csv", "95%"],
] as const;
const graphNodes = [
  { id: "phone", label: "+91 98765 43210", kind: "PHONE", x: 12, y: 25, icon: Activity, tone: "bg-[#fff1ee] text-[#9c3029]" },
  { id: "upi", label: "r***l@okaxis", kind: "UPI HANDLE", x: 45, y: 52, icon: CircleDollarSign, tone: "bg-[#fdf5e7] text-[#9c6723]" },
  { id: "url", label: "job-offer[.]in", kind: "DOMAIN", x: 76, y: 24, icon: Globe, tone: "bg-[#eef6f3] text-[#357456]" },
  { id: "payment", label: "₹30,000", kind: "PAYMENT", x: 77, y: 76, icon: Landmark, tone: "bg-[#f1eef8] text-[#62508f]" },
  { id: "chat", label: "chat_export.txt", kind: "SOURCE", x: 18, y: 76, icon: Files, tone: "bg-[#eef4fa] text-[#356787]" },
] as const;
const graphEdges = ["M21 31 C30 36 35 43 45 52", "M53 48 C62 39 67 30 76 25", "M52 56 C61 63 69 71 77 76", "M22 71 C30 63 37 58 45 54"];

function PreviewChip({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "green" | "red" | "amber" }) {
  const styles = { neutral: "border-[#ded6cb] bg-white text-[#6a6259]", green: "border-[#c8dfcf] bg-[#eff8f1] text-[#327142]", red: "border-[#e9c9c4] bg-[#fff0ee] text-[#9a3029]", amber: "border-[#ead9b8] bg-[#fff8e9] text-[#9a6725]" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[8px] font-extrabold ${styles[tone]}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{children}</span>;
}

function PreviewHeader({ pane }: { pane: Pane }) {
  return <div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="text-lg font-extrabold text-[#322b26]">{pane}</p><PreviewChip tone="amber">STATIC DEMO</PreviewChip></div><p className="mt-1 text-[11px] text-[#786f65]">Fictional case-preview surface · frontend only</p></div><button type="button" aria-label="Preview search" className="grid h-9 w-9 place-items-center rounded-md border border-[#ddd4c9] bg-white text-[#7f1d1d] transition hover:-translate-y-0.5 hover:border-[#b36b62]"><Search size={16}/></button></div>;
}

function TimelinePane() {
  return <div className="relative mt-7 space-y-4 before:absolute before:bottom-2 before:left-[7px] before:top-2 before:w-px before:bg-[#d4c5b7]">{timeline.map(([time, title, detail, source, confidence], index) => <div key={time} className="relative pl-9"><span className={`absolute left-0 top-1 grid h-[15px] w-[15px] place-items-center rounded-full border-4 border-[#fffdf8] ${index === 2 ? "bg-[#7f1d1d] shadow-[0_0_0_4px_rgba(127,29,29,.1)]" : "bg-[#b7a694]"}`}/><div className="flex flex-col justify-between gap-2 rounded-xl border border-[#e7dfd3] bg-white p-4 transition hover:-translate-y-0.5 hover:border-[#c7a7a0] sm:flex-row"><div><p className="mono text-[10px] text-[#7f1d1d]">{time} IST</p><p className="mt-1 text-xs font-extrabold text-[#322b26]">{title}</p><p className="mt-1 text-[11px] text-[#6d665d]">{detail}</p></div><div className="flex items-end gap-2 sm:flex-col sm:items-end"><span className="mono text-[9px] text-[#80776b]">{source}</span><PreviewChip tone="green">{confidence}</PreviewChip></div></div></div>)}</div>;
}

function GraphPane() {
  const [selected, setSelected] = useState<(typeof graphNodes)[number]>(graphNodes[1]);
  const selectedDetail = useMemo(() => selected.id === "upi" ? "Matched in payment receipt and bank debit reference." : selected.id === "url" ? "Shared inside the fictional chat source." : selected.id === "payment" ? "Fictional UPI transfer connected to the handle." : selected.id === "chat" ? "Original demo source containing the first lead." : "Phone identifier referenced in the fictional job offer.", [selected]);
  return <div className="mt-7 grid gap-4 xl:grid-cols-[1fr_190px]"><section className="relative min-h-[330px] overflow-hidden rounded-xl border border-[#e3d9cc] bg-[#fcfaf5] [background-image:radial-gradient(#dccfc0_0.7px,transparent_0.7px)] [background-size:13px_13px]"><div className="absolute left-4 top-4 flex items-center gap-2"><PreviewChip tone="green">5 entities</PreviewChip><PreviewChip>4 links</PreviewChip></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="pointer-events-none absolute inset-0 h-full w-full" aria-hidden="true">{graphEdges.map((path, index) => <path key={path} d={path} fill="none" stroke={index === 2 ? "#a67335" : "#9e3730"} strokeWidth="0.55" strokeDasharray="2 1.6" className="animate-pulse" style={{ animationDelay: `${index * 180}ms` }}/>)}</svg>{graphNodes.map((node) => { const Icon = node.icon; return <button type="button" onClick={() => setSelected(node)} key={node.id} style={{ left: `${node.x}%`, top: `${node.y}%` }} className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-xl border p-2 text-left shadow-[0_8px_18px_rgba(82,49,36,.08)] transition duration-200 hover:-translate-y-[55%] hover:shadow-[0_12px_22px_rgba(127,29,29,.16)] ${selected.id === node.id ? "border-[#9e3730] bg-white ring-4 ring-[#9e3730]/10" : "border-[#e5d9ca] bg-[#fffdfa]"}`}><span className={`grid h-8 w-8 place-items-center rounded-lg ${node.tone}`}><Icon size={15}/></span><small className="mt-2 block max-w-[88px] truncate text-[7px] font-extrabold text-[#8e413a]">{node.kind}</small><b className="mt-0.5 block max-w-[88px] truncate text-[9px] text-[#372e28]">{node.label}</b></button>})}<div className="absolute bottom-4 left-4 flex items-center gap-2 text-[8px] font-bold text-[#84776c]"><Link2 size={12} className="text-[#9e3730]"/> click a node to inspect its fictional connection</div></section><aside className="rounded-xl border border-[#e3d9cc] bg-white p-4"><p className="text-[8px] font-extrabold uppercase tracking-[.14em] text-[#994038]">Selected entity</p><p className="mt-3 text-[13px] font-extrabold text-[#342b25]">{selected.label}</p><PreviewChip tone="amber">{selected.kind}</PreviewChip><p className="mt-4 text-[10px] leading-5 text-[#71665b]">{selectedDetail}</p><div className="mt-5 border-t border-[#eee4d8] pt-4"><p className="mono text-[8px] text-[#8e413a]">SOURCE / DF-2026-1147</p><p className="mt-1 text-[9px] text-[#776b60]">Static demo relationship map</p></div></aside></div>;
}

function TransactionsPane() {
  const rows = [["10:42", "r***l@okaxis", "₹30,000", "UPI receipt", "Matched"], ["10:48", "Bank debit", "₹30,000", "bank_may.csv", "Confirmed"], ["11:02", "merchant-trail", "₹14,500", "gateway export", "Review"]] as const;
  return <div className="mt-7 overflow-hidden rounded-xl border border-[#e5dbcf] bg-white"><div className="flex items-center justify-between border-b border-[#eee4d8] bg-[#fff8f1] px-4 py-3"><span><p className="text-[10px] font-extrabold text-[#3b302a]">Fictional payment trail</p><p className="mt-1 text-[9px] text-[#81756a]">A static reconstruction linked to the timeline demo.</p></span><CircleDollarSign size={20} className="text-[#9e3730]"/></div><div className="divide-y divide-[#f0e7dc]">{rows.map(([time, handle, amount, source, state], index) => <button type="button" key={time} className="grid w-full grid-cols-[52px_1fr_auto] items-center gap-3 px-4 py-4 text-left transition hover:bg-[#fffaf4]"><span className="mono text-[9px] font-bold text-[#9e3730]">{time}</span><span><b className="block text-[11px] text-[#392f29]">{handle}</b><small className="mt-1 block text-[9px] text-[#81756a]">{source} · fictional source trail</small></span><span className="text-right"><b className="block text-[12px] text-[#3c3028]">{amount}</b><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[8px] font-bold ${index === 2 ? "bg-[#fff4de] text-[#9a6725]" : "bg-[#eff8f1] text-[#347446]"}`}>{state}</span></span></button>)}</div><div className="flex items-center justify-between border-t border-[#eee4d8] bg-[#fcfaf6] px-4 py-3"><span className="text-[9px] font-bold text-[#81756a]">3 linked transfer references</span><span className="text-[11px] font-extrabold text-[#8f342e]">₹44,500 traced</span></div></div>;
}

function AlertsPane() {
  const alerts = [["Repeated payment handle", "r***l@okaxis appears across two fictional sources.", "High", "red"], ["Missing email header", "Header fields were not available in the preview source.", "Medium", "amber"], ["Timestamp gap", "20-minute gap between chat and transfer references.", "Review", "neutral"]] as const;
  return <div className="mt-7 grid gap-3">{alerts.map(([title, note, severity, tone], index) => <button type="button" key={title} className="group flex items-start gap-4 rounded-xl border border-[#e6ddd1] bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-[#caa69e]"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-lg ${index === 0 ? "bg-[#fff0ee] text-[#9c3029]" : index === 1 ? "bg-[#fff6e5] text-[#a46b1e]" : "bg-[#eef2f4] text-[#536674]"}`}><AlertTriangle size={18}/></span><span className="min-w-0 flex-1"><b className="block text-[11px] text-[#362c26]">{title}</b><small className="mt-1.5 block text-[10px] leading-5 text-[#74675c]">{note}</small></span><PreviewChip tone={tone as "red" | "amber" | "neutral"}>{severity}</PreviewChip></button>)}</div>;
}

function EvidencePane() {
  const evidence = [[Files, "chat_export.txt", "Conversation", "Hash verified", "green"], [FileText, "upi_receipt.png", "Payment proof", "Linked", "green"], [Database, "bank_may.csv", "Statement", "Normalized", "amber"], [Globe, "job-offer[.]in", "Domain lead", "Review", "red"]] as const;
  return <div className="mt-7 grid gap-3 sm:grid-cols-2">{evidence.map(([Icon, file, kind, state, tone], index) => <button type="button" key={file} className="relative overflow-hidden rounded-xl border border-[#e5dbcf] bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-[#c4a298]"><i className="absolute -right-3 -top-5 h-20 w-20 rounded-full border-[13px] border-[#fff3ed] opacity-75"/><span className="relative flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#f7eee9] text-[#9d3830]"><Icon size={18}/></span><span className="mono text-[8px] text-[#9a473f]">0{index + 1}</span></span><b className="relative mt-5 block truncate text-[11px] text-[#382e28]">{file}</b><small className="relative mt-1 block text-[9px] text-[#776b60]">{kind} · fictional demo item</small><span className="relative mt-3 inline-flex"><PreviewChip tone={tone as "green" | "amber" | "red"}>{state}</PreviewChip></span></button>)}</div>;
}

function ReportPane() {
  const lines = ["Chronology of four source-linked events", "Five linked entity and payment references", "Three reviewable caveats retained", "Hash and source appendix prepared"];
  return <div className="mt-7 grid gap-4 lg:grid-cols-[1fr_180px]"><article className="relative overflow-hidden rounded-xl border border-[#dfd4c6] bg-white p-5 shadow-[0_10px_24px_rgba(82,49,36,.06)]"><div className="absolute right-5 top-5 rounded-full border border-[#ead9cf] bg-[#fff8f2] px-2 py-1 mono text-[8px] text-[#9e3730]">DRAFT / 01</div><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#963b34]">Fictional case report</p><h3 className="mt-3 font-serif text-xl font-bold text-[#322820]">Job offer & payment trail</h3><p className="mt-2 max-w-md text-[10px] leading-5 text-[#74675c]">A static report-builder preview showing how sources, caveats, and decision notes are organized.</p><div className="mt-5 space-y-3">{lines.map((line) => <div key={line} className="flex items-center gap-3 border-b border-[#f0e6da] pb-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#f7ebe6] text-[#963b34]"><ShieldCheck size={11}/></span><span className="text-[10px] font-bold text-[#544840]">{line}</span></div>)}</div></article><aside className="rounded-xl border border-[#e3d9cc] bg-[#fff8f1] p-4"><Sparkles size={18} className="text-[#9e3730]"/><p className="mt-3 text-[11px] font-extrabold text-[#3c3029]">Review gate</p><p className="mt-2 text-[10px] leading-5 text-[#796d61]">A report remains a draft until investigators review all flagged demo items.</p><button type="button" className="mt-5 w-full rounded-lg bg-[#7f1d1d] px-3 py-2 text-[9px] font-bold text-white transition hover:bg-[#691919] active:scale-[.97]">Preview report flow</button></aside></div>;
}

function OverviewPane() {
  return <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Network, "5", "linked entities", "bg-[#fff0ed] text-[#9d362e]"], [Files, "4", "source records", "bg-[#eef5fb] text-[#38698a]"], [CircleDollarSign, "₹44.5K", "transfer references", "bg-[#fff6e6] text-[#a76c22]"], [AlertTriangle, "3", "reviewable alerts", "bg-[#f4eef9] text-[#70518b]"]].map(([Icon, value, label, style]) => { const I = Icon as typeof Network; return <article key={String(label)} className="rounded-xl border border-[#e4dbcf] bg-white p-4"><span className={`grid h-9 w-9 place-items-center rounded-lg ${style as string}`}><I size={17}/></span><b className="mt-5 block text-xl text-[#342a24]">{value as string}</b><small className="mt-1 block text-[9px] text-[#776b60]">{label as string} · demo</small></article>})}</div>;
}

function PaneContent({ pane }: { pane: Pane }) {
  if (pane === "Timeline") return <TimelinePane/>;
  if (pane === "Entity graph") return <GraphPane/>;
  if (pane === "Transaction trail") return <TransactionsPane/>;
  if (pane === "Alerts") return <AlertsPane/>;
  if (pane === "Evidence vault") return <EvidencePane/>;
  if (pane === "Report builder") return <ReportPane/>;
  return <OverviewPane/>;
}

export default function PublicCasePreview() {
  const [activePane, setActivePane] = useState<Pane>("Timeline");
  return <div className="paper-shadow mt-10 overflow-hidden rounded-[22px] border border-[#ddd3c6] bg-[#fffdf8]"><div className="flex flex-col border-b border-[#e6ddd1] bg-[#fbf8f1] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#7f1d1d] text-white"><Files size={17}/></span><div><p className="text-sm font-extrabold text-[#342a25]">DEMO — Fictional UPI job-offer fraud</p><p className="mono mt-1 text-[10px] text-[#716b62]">DF-2026-1147 · Static frontend preview</p></div></div><div className="mt-3 flex gap-2 sm:mt-0"><PreviewChip tone="red">High priority</PreviewChip><PreviewChip tone="green">Preview active</PreviewChip></div></div><div className="grid min-h-[540px] lg:grid-cols-[205px_1fr_265px]"><aside className="border-b border-[#e7ded3] bg-[#f5f0e7] p-3 lg:border-b-0 lg:border-r"><p className="px-3 pb-3 pt-2 text-[9px] font-extrabold uppercase tracking-[.16em] text-[#8b8277]">Case views</p>{panes.map((item) => <button type="button" onClick={() => setActivePane(item)} key={item} className={`mb-1 flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-xs font-bold transition ${activePane === item ? "bg-[#7f1d1d] text-white shadow-sm" : "text-[#4f4a43] hover:bg-[#eae3d8]"}`}><span className="h-1.5 w-1.5 rounded-full bg-current opacity-70" />{item}</button>)}</aside><div className="relative overflow-hidden p-5 sm:p-7"><PreviewHeader pane={activePane}/><div className="animate-in fade-in slide-in-from-bottom-1 duration-300"><PaneContent pane={activePane}/></div></div><aside className="border-t border-[#e7ded3] bg-[#fbf8f1] p-5 lg:border-l lg:border-t-0"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#8b8277]">Lead summary</p><div className="mt-5 rounded-xl border border-[#ead5d2] bg-[#fff5f3] p-4"><div className="flex items-center gap-2 text-[#9c2c25]"><AlertTriangle size={17}/><p className="text-[11px] font-extrabold">3 reviewable alerts</p></div><p className="mt-3 text-[11px] leading-5 text-[#6c5650]">Missing email header, repeated UPI handle, and a timestamp gap require investigator review.</p></div><div className="mt-5 space-y-3">{[["Entities", "5 illustrated"], ["Evidence", "4 demo sources"], ["Confidence", "93.4% demo"], ["Hash status", "Preview only"]].map(([key, value]) => <div key={key} className="flex items-center justify-between border-b border-[#e8e0d5] pb-3 text-[11px]"><span className="text-[#777066]">{key}</span><span className="font-extrabold text-[#40352e]">{value}</span></div>)}</div><div className="mt-5 rounded-xl border border-[#e6ddd1] bg-white p-3"><Clock size={15} className="text-[#9c3029]"/><p className="mt-2 text-[9px] font-bold text-[#655a50]">Interactive static preview</p><p className="mt-1 text-[9px] leading-4 text-[#8b7f73]">This Home-page demo does not read or write case data.</p></div></aside></div></div>;
}
