"""initial backend schema

Revision ID: 157344c6c510
Revises: 
Create Date: 2026-08-22 09:08:03.413764
"""
from alembic import op
import sqlalchemy as sa

revision = '157344c6c510'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('INVESTIGATOR', 'REVIEWER', 'BANK_ANALYST', 'ADMIN', name='role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('crime_type', sa.String(length=120), nullable=False),
    sa.Column('fir_number', sa.String(length=120), nullable=True),
    sa.Column('victim_alias', sa.String(length=160), nullable=True),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'CLOSED', 'ARCHIVED', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_owner_id'), 'cases', ['owner_id'], unique=False)
    op.create_index('ix_cases_status_updated', 'cases', ['status', 'updated_at'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_case_created', 'audit_logs', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_table('case_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('case_role', sa.Enum('INVESTIGATOR', 'REVIEWER', 'BANK_ANALYST', 'ADMIN', name='case_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_case_membership')
    )
    op.create_table('evidence_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('stored_name', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('source_category', sa.String(length=64), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('declared_mime', sa.String(length=128), nullable=True),
    sa.Column('detected_mime', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'HASHING', 'QUEUED', 'PROCESSING', 'OCR', 'EXTRACTING', 'NORMALIZING', 'BUILDING_GRAPH', 'EVALUATING_ALERTS', 'AWAITING_REVIEW', 'COMPLETED', 'FAILED', name='evidence_status'), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', 'version', name='uq_evidence_case_hash_version'),
    sa.UniqueConstraint('storage_key'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index('ix_evidence_case_status_uploaded', 'evidence_files', ['case_id', 'status', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_evidence_files_case_id'), 'evidence_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_sha256'), 'evidence_files', ['sha256'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', name='report_state'), nullable=False),
    sa.Column('review_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('redaction_profile', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('generated_by_id', sa.String(length=36), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version', name='uq_report_case_version'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'REJECTED', 'NEEDS_MORE_EVIDENCE', name='review_decision_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_case_id'), 'review_decisions', ['case_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_time', sa.String(length=128), nullable=True),
    sa.Column('time_precision', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_text_reference', sa.String(length=512), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'REJECTED', 'NEEDS_MORE_EVIDENCE', name='event_review_status'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['evidence_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index('ix_events_case_time', 'events', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_table('extracted_text',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'pipeline_version', name='uq_extracted_text_version')
    )
    op.create_index(op.f('ix_extracted_text_evidence_id'), 'extracted_text', ['evidence_id'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=80), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', name='processing_state'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('warning_messages', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'pipeline_stage', 'pipeline_version', name='uq_processing_stage_version')
    )
    op.create_index(op.f('ix_processing_runs_celery_task_id'), 'processing_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_processing_runs_evidence_id'), 'processing_runs', ['evidence_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWED', 'DISMISSED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('affected_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('related_event_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index('ix_alerts_case_status_severity', 'alerts', ['case_id', 'status', 'severity'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_evidence_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'REJECTED', 'NEEDS_MORE_EVIDENCE', name='entity_review_status'), nullable=False),
    sa.Column('first_seen_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_seen_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index('ix_entities_case_type_normalized', 'entities', ['case_id', 'entity_type', 'normalized_value'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('source_evidence_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_id', sa.String(length=160), nullable=True),
    sa.Column('sender_value', sa.String(length=256), nullable=True),
    sa.Column('receiver_value', sa.String(length=256), nullable=True),
    sa.Column('source_kind', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'REJECTED', 'NEEDS_MORE_EVIDENCE', name='transaction_review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_case_id'), 'transactions', ['case_id'], unique=False)
    op.create_index('ix_transactions_case_time', 'transactions', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_table('event_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'entity_id', 'relationship_type', name='uq_event_entity_relation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_entities')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index('ix_transactions_case_time', table_name='transactions')
    op.drop_index(op.f('ix_transactions_case_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_entities_case_type_normalized', table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_alerts_case_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_processing_runs_evidence_id'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_celery_task_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_extracted_text_evidence_id'), table_name='extracted_text')
    op.drop_table('extracted_text')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index('ix_events_case_time', table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_review_decisions_case_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_evidence_files_sha256'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_case_id'), table_name='evidence_files')
    op.drop_index('ix_evidence_case_status_uploaded', table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_table('case_memberships')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_case_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index('ix_cases_status_updated', table_name='cases')
    op.drop_index(op.f('ix_cases_owner_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

